id = "freshjuice-hubl"
name = "HubSpot HubL by FreshJuice"
description = "HubL syntax highlighting for HubSpot templates"
version = "1.0.0"
schema_version = 1
authors = ["Alex Zappa @ FreshJuice.dev"]
repository = "https://github.com/freshjuice-dev/zed-hubl"

[grammars.hubl]
repository = "https://github.com/freshjuice-dev/zed-hubl"
path = "grammar"
rev = "a62aaaf892904fac6d6bbeea79ccd674f1ddb785"
